services:

  app:
    build: .
    container_name: backend-api
    ports:
      - "10000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST=http://ollama:11434
      - REMBG_URL=http://rembg-service:8001
      - OCR_MODEL=glm-ocr:bf16
      - VISION_MODEL=gemma4:26b
      - TEXT_EMBED_MODEL=bge-m3:latest
      - IMAGE_DEST=/app/images/processed
      - THUMB_DEST=/app/images/thumbnails
      - DEBUG_DIR=/app/debug
    env_file:
      - .env
    volumes:
      - ./source/Sistema-de-catalogacion-de-imagenes:/app/src
      - C:/Users/User/Documents/ProyectoEtiquetas/procesadas:/app/images/processed
      - C:/Users/User/Documents/ProyectoEtiquetas/miniaturas:/app/images/thumbnails
      - C:/Users/User/Documents/ProyectoEtiquetas/debug:/app/debug
    networks:
      - red-proyecto
      - proyectocontabilidad_contabilidad-network
    restart: unless-stopped

  rembg-service:
    build: ./rembg-service
    container_name: rembg-service
    ports:
      - "8001:8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - red-proyecto
    restart: unless-stopped

networks:
  red-proyecto:
    driver: bridge
  proyectocontabilidad_contabilidad-network:
    external: true

volumes:
  hf_cache: